/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface EngHeader {}
  interface EngHeaderAttributes extends StencilHTMLAttributes {}

  interface EngSecondarySidebar {}
  interface EngSecondarySidebarAttributes extends StencilHTMLAttributes {}

  interface EngSidebar {}
  interface EngSidebarAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EngHeader': Components.EngHeader;
    'EngSecondarySidebar': Components.EngSecondarySidebar;
    'EngSidebar': Components.EngSidebar;
  }

  interface StencilIntrinsicElements {
    'eng-header': Components.EngHeaderAttributes;
    'eng-secondary-sidebar': Components.EngSecondarySidebarAttributes;
    'eng-sidebar': Components.EngSidebarAttributes;
  }


  interface HTMLEngHeaderElement extends Components.EngHeader, HTMLStencilElement {}
  var HTMLEngHeaderElement: {
    prototype: HTMLEngHeaderElement;
    new (): HTMLEngHeaderElement;
  };

  interface HTMLEngSecondarySidebarElement extends Components.EngSecondarySidebar, HTMLStencilElement {}
  var HTMLEngSecondarySidebarElement: {
    prototype: HTMLEngSecondarySidebarElement;
    new (): HTMLEngSecondarySidebarElement;
  };

  interface HTMLEngSidebarElement extends Components.EngSidebar, HTMLStencilElement {}
  var HTMLEngSidebarElement: {
    prototype: HTMLEngSidebarElement;
    new (): HTMLEngSidebarElement;
  };

  interface HTMLElementTagNameMap {
    'eng-header': HTMLEngHeaderElement
    'eng-secondary-sidebar': HTMLEngSecondarySidebarElement
    'eng-sidebar': HTMLEngSidebarElement
  }

  interface ElementTagNameMap {
    'eng-header': HTMLEngHeaderElement;
    'eng-secondary-sidebar': HTMLEngSecondarySidebarElement;
    'eng-sidebar': HTMLEngSidebarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
